# Generated by Django 6.0.4 on 2026-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmentsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
