# Generated by Django 6.0.4 on 2026-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmentsystem', '0003_alter_student_address_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
